package com.wonders.deptDoc.model.bo;

// Generated 2014-10-15 14:49:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * ZDocsCatalog generated by hbm2java
 */
@Entity
@Table(name = "Z_DOCS_CATALOG")
public class ZDocsCatalog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8277970112216924578L;
	private String sid;
	private String catalogName;
	private String parentSid;
	private String deptId;
	private String state;
	private String createUser;
	private String createUserName;
	private Date createDate;
	private String updateUser;
	private String updateUserName;
	private Date updateDate;
	private String readRight;
	private String writeRight;
	private String flag;


	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "SID", unique = true, nullable = false, length = 100)
	public String getSid() {
		return this.sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	@Column(name = "CATALOG_NAME", length = 200)
	public String getCatalogName() {
		return this.catalogName;
	}

	public void setCatalogName(String catalogName) {
		this.catalogName = catalogName;
	}

	@Column(name = "PARENT_SID", length = 100)
	public String getParentSid() {
		return this.parentSid;
	}

	public void setParentSid(String parentSid) {
		this.parentSid = parentSid;
	}

	@Column(name = "STATE", length = 1)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "CREATE_USER", length = 50)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE")
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_USER", length = 50)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE")
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "READ_RIGHT", length = 50)
	public String getReadRight() {
		return this.readRight;
	}

	public void setReadRight(String readRight) {
		this.readRight = readRight;
	}

	@Column(name = "WRITE_RIGHT", length = 50)
	public String getWriteRight() {
		return this.writeRight;
	}

	public void setWriteRight(String writeRight) {
		this.writeRight = writeRight;
	}

	@Column(name = "FLAG", length = 50)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "DEPT_ID", length = 50)
	public String getDeptId() {
		return deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name = "CREATE_USER_NAME", length = 50)
	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	
	@Column(name = "UPDATE_USER_NAME", length = 50)
	public String getUpdateUserName() {
		return updateUserName;
	}

	public void setUpdateUserName(String updateUserName) {
		this.updateUserName = updateUserName;
	}

	
}
